# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AegisFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=256)),
                ('fn_md5', models.CharField(max_length=128, unique=True)),
                ('ext', models.CharField(default='.html', max_length=8)),
                ('crt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-crt'],
                'db_table': 'aegis_file',
            },
        ),
    ]
