# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRecordsMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('crt', models.DateTimeField(auto_now=True)),
                ('spider_task_id', models.UUIDField()),
                ('consumer_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('used_pages_amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'aegis_consumer_records',
            },
        ),
        migrations.CreateModel(
            name='MiddleFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('crt', models.DateTimeField(auto_now=True)),
                ('spider_task_id', models.UUIDField()),
                ('url', models.URLField(max_length=256)),
                ('filename', models.CharField(max_length=128, unique=True)),
                ('ext', models.CharField(default='.html', max_length=8)),
                ('file_utility', models.CharField(choices=[('HT', 'Html'), ('PM', 'Parameter')], max_length=2)),
            ],
            options={
                'db_table': 'aegis_middle_file',
            },
        ),
        migrations.CreateModel(
            name='SpiderTasksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('crt', models.DateTimeField(auto_now=True)),
                ('spider_name', models.CharField(max_length=126)),
                ('spider_task_id', models.UUIDField()),
                ('spider_description', models.CharField(max_length=1024)),
                ('robotstxt_obey', models.BooleanField(default=True)),
                ('cookies_enabled', models.BooleanField(default=True)),
                ('download_delay', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('concurrent_requests', models.IntegerField(default=16)),
                ('other_configure', models.TextField(default='{}')),
                ('request_method', models.CharField(default='GET', max_length=8)),
                ('request_cookies', models.TextField()),
                ('request_headers', models.TextField()),
                ('proxy_ip_enabled', models.BooleanField(default=False)),
                ('login_username', models.CharField(max_length=32)),
                ('login_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'aegis_spider_tasks',
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('crt', models.DateTimeField(auto_now=True)),
                ('pay_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('pay_mode', models.CharField(choices=[('WX', 'WeChat'), ('AP', 'Alipay')], max_length=2)),
                ('pages_amount', models.IntegerField(default=150)),
            ],
            options={
                'db_table': 'aegis_wallet',
            },
        ),
        migrations.DeleteModel(
            name='AegisFileModel',
        ),
    ]
