# -*- coding: utf-8 -*-

"""
Django settings for apollo project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-0&(0d-r!lj89%zdc(o59mce6$-ivrx%)he6j!z0gv%j*fj01&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Packages App
    'corsheaders',
    'rest_framework',
    'django_celery_results',

    # Self-Defined App
    'apps.accounts',
    'apps.aegis',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',  # # 注意与`django-cors-headers`顺序
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apollo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_00',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',

        'OPTIONS': {
            # 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            # 'init_command': "SET foreign_key_checks = 0;",
        }
    },

    'apollo': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apollo_00',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',

        'OPTIONS': {
            # 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'init_command': "SET foreign_key_checks = 0;'",
        }
    },

    # 'mongo': {
    #    "ENGINE": 'django.db.backends.dummy'
    # },

}

# Start Configure `DATABASE_ROUTERS` settings
# 暂时先不分库分表，多机器分库时，产生如下错误：
# owner = models.ForeignKey('auth.User', null=True, blank=True,
#                          related_name='owners', on_delete=models.SET_NULL)
# django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
# Guess: ForeignKey 无法支持多机器分库
#
DATABASE_ROUTERS = ['apollo.database_router.DatabaseAppsRouter']
DATABASE_APPS_MAPPING = {
    'django_celery_results': 'apollo',
    'accounts': 'apollo',
    'aegis': 'apollo'
}
# End Configure `DATABASE_ROUTERS` settings

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# Start Send Mail Config
EMAIL_HOST = 'smtp.163.com'
EMAIL_HOST_USER = 'xutaoding@163.com'
EMAIL_HOST_PASSWORD = '5869654tao'
EMAIL_SUBJECT_PREFIX = u'宙斯盾平台确认码'
EMAIL_USE_TLS = False
# End Send Mail Config

# Rest Framework settings Start
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated accounts.

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.DjangoObjectPermissions',
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),

    'PAGINATE_BY': 10
}
# Rest Framework settings End

# `rest_framework_jwt` settings start
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=300),  # expired time
    'JWT_AUTH_HEADER_PREFIX': 'JWT-ABC',  # request header prefix
    'JWT_AUTH_COOKIE': 'drf-apo',

    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7)
}
# `rest_framework_jwt` settings start end


# Start `django-cors-headers` middleware Settings
# 跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ['*']

CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'VIEW', )
CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)
# End `django-cors-headers` middleware Settings

# HTML Web Path Settings Start
HTML_FILE_PATH = '/data/aegis_html'
if not os.path.exists(HTML_FILE_PATH):
    os.makedirs(HTML_FILE_PATH)
# HTML Web Path Settings End

